#!/usr/bin/env bash

#
# My additions
#
mkdir ~/.ssh
mkdir ~/.config/nvim/
mkdir ~/Library/Application\ Support/Code/
mkdir ~/Library/Application\ Support/Code/User/

#
# Dotbot default script follows
#
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
